apiVersion: v1
# Kind for kubernets ConfigMap
kind: ConfigMap
metadata:
  # Name your ConfigMap
  name: db-secret-credentials
  labels:
    app: postgresdb
data:
  # User DB
  POSTGRES_DB: netnet
  # Db user
  POSTGRES_USER: netnet
  # Db password
  POSTGRES_PASSWORD: '5&T#0upcg96xYBz2u2'
